# Generated by Django 4.2.6 on 2023-11-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Punto Verde')),
                ('adress', models.CharField(max_length=250, verbose_name='Direccion')),
                ('state', models.CharField(max_length=250, verbose_name='Estado')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Punto Verde',
                'verbose_name_plural': 'Puntos Verdes',
                'ordering': ['name'],
            },
        ),
    ]
